services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4000:3000"
    env_file:
      - ./.env

    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev